version: '3.8'
services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  device-sim:
    build: ./devices
    depends_on:
      - mqtt-broker
    environment:
      MQTT_BROKER: mqtt-broker
      MQTT_PORT: 1883
      DEVICE_ID: device01
    restart: unless-stopped
