version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    network_mode: host
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  device-sim:
    build: ./devices
    network_mode: host
    environment:
      MQTT_BROKER: localhost
      MQTT_PORT: 1883
      DEVICE_ID: device01
    restart: unless-stopped

  threat-emulator:
    build: ./threat-emulator
    network_mode: host
    environment:
      MQTT_BROKER: localhost
      MQTT_PORT: 1883
    restart: "no"

  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    cap_add:                # minimal, but sufficient, capability set
      - NET_ADMIN           # open AF_PACKET sockets
      - NET_RAW
      - SETUID              # drop uid
      - SETGID              # drop gid
      - SETPCAP             # keep caps after dropping privileges
    network_mode: host
    user: root              # start as root, then Suricata demotes itself
    volumes:
      - ./suricata.yaml:/etc/suricata/suricata.yaml:ro
      - ./rules:/etc/suricata/rules:ro
      - suricata-logs:/var/log/suricata
    command:
      [
        "-c", "/etc/suricata/suricata.yaml",
        "-i", "ens33",
        "--init-errors-fatal"
      ]
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.6.0
    depends_on:
      - elasticsearch
      - suricata
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/:ro
      - suricata-logs:/var/log/suricata:ro
    ports:
      - "5044:5044"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"

volumes:
  es-data:
  suricata-logs: