version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  device-sim:
    build: ./devices
    depends_on:
      - mqtt-broker
    environment:
      MQTT_BROKER: mqtt-broker
      MQTT_PORT: 1883
      DEVICE_ID: device01
    restart: unless-stopped

  suricata:
    image: jasonish/suricata:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: "service:mqtt-broker"
    volumes:
      - ./suricata.yaml:/etc/suricata/suricata.yaml:ro
      - suricata-logs:/var/log/suricata
    command: ["-i", "eth0", "-c", "/etc/suricata/suricata.yaml", "--init-errors-fatal=yes"]

  threat-emulator:
    build: ./threat-emulator
    depends_on:
      - mqtt-broker
      - suricata
    environment:
      MQTT_BROKER: mqtt-broker
      MQTT_PORT: 1883
    network_mode: "service:mqtt-broker"
    restart: "no"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

    logstash:
      image: docker.elastic.co/logstash/logstash:8.6.0
      depends_on:
        - elasticsearch
        - suricata
      volumes:
        - ./logstash/pipeline/:/usr/share/logstash/pipeline/:ro
        - suricata-logs:/var/log/suricata:ro
      ports:
        - "5044:5044"

    kibana:
      image: docker.elastic.co/kibana/kibana:8.6.0
      depends_on:
        - elasticsearch
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        - xpack.security.enabled=false
      ports:
        - "5601:5601"

volumes:
  es-data:
  suricata-logs: